name: Bicep Template Build and Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
    - main
    - templates
  pull_request:
    branches: main 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
# JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      securelab: ${{ steps.filter.outputs.securelab }}
      accpmk: ${{ steps.filter.outputs.accpmk }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: actions/checkout@v2
    
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          securelab:
            - 'templates/10-Secure-Lab-Environment/Bicep-Templates/*.bicep'
          accpmk:
            - 'templates/01-ACC-VM-Platform-Key/Bicep-Templates/*.bicep'

  # JOB to build and test securelab bicep templates
  securelab:
    name: Secure Lab Bicep Build and Test

    needs: changes
    if: ${{ needs.changes.outputs.securelab == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Bicep build
        uses: aliencube/bicep-build-actions@v0.1
        with:
          files: 'templates/10-Secure-Lab-Environment/Bicep-Templates/main.bicep'

      - name: Run ARM TTK
        uses: aliencube/arm-ttk-actions@v0.3
        id: securetest
        with:
          path: ./templates/10-Secure-Lab-Environment/Bicep-Templates/main.json

      - name: Test result - path
        shell: bash
        continue-on-error: true
        run: |
          echo "${{ toJSON(fromJSON(steps.securetest.outputs.results)) }}"         
    
  accpmk:
    name: ACC PMK Bicep Build and Test

    needs: changes
    if: ${{ needs.changes.outputs.accpmk == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Bicep build
        uses: aliencube/bicep-build-actions@v0.1
        with:
          files: 'templates/01-ACC-VM-Platform-Key/Bicep-Templates/main.bicep'

      - name: Run ARM TTK
        uses: aliencube/arm-ttk-actions@v0.3
        id: accpmktest
        with:
          path: ./templates/01-ACC-VM-Platform-Key/Bicep-Templates/main.json

      - name: Test result - path
        shell: bash
        continue-on-error: true
        run: |
          echo "${{ toJSON(fromJSON(steps.accpmktest.outputs.results)) }}"  